const db  = require('./database/dbConn.js');
const express = require('express');
const check = require('./api/check.js');
const {isStringArray} = require("./api/check");
const {ObjectId} = require("mongodb");
const port = 8080;
const app = express();

// root sends welcome message
app.get('/', (req, res) => {
    res.send('Welcome to the Nimbase Back-end API!');
});


app.get('/api', async (req, res) => {
    const collection = db.collection("users");
    const result = await collection.find({}).toArray();
    res.send(result);
});

/****** USER COLLECTION *****************/
/**
 * schema:
 * {
 *   _id: ObjectId,
 *   username: string,
 *   password_hash: string,
 *   email: string,
 *   project_ids: ObjectId[],
 * }
 * note: do not include _id in create new user requests as this is auto-generated by mongodb
 * note: do not project_ids in create new user requests as this starts off empty
 */

// create a new user
// REQUIRES: JSON body matching user schema
// REQUIRES: username is not already taken
// REQUIRES: email is not already taken
app.post('/api/user', express.json(), async (req, res) => {
    if (!check.isNewUser(req.body)) {
        if (!check.isEmail(req.body.email)) {
            res.status(400).send("need email -> valid email string in request body");
            return;
        }
        res.status(400).send("invalid new user in request body (as json)");
        return
    }
    const users = db.collection("users");

    if (await users.findOne({username: req.body.username})) {
        res.status(400).send("username already taken");
        return;
    }
    if (await users.findOne({email: req.body.email})) {
        res.status(400).send("email already taken");
        return;
    }
    const result = await users.insertOne({...req.body, project_ids: []});
    res.status(200).send(result);
});

// get all projects (ids) of a user
app.get('/api/user/projects', express.json(), async (req, res) => {
    if (!check.isString(req.body.username)) {
        res.status(400).send("need username -> string in request body");
        return;
    }
    const users = db.collection("users");
    const result = await users.findOne({username: req.body.username}, {projection: {_id: 0, project_ids: 1}});
    if (!result) {res.status(404).send(result);}
    if (!isStringArray(result.project_ids)) {console.error("result.project_ids should have been a string array");}
    res.status(200).send(result);
});

//authenticate/login user
app.post('/api/user/login', async (req, res) => {
    // const users = db.collection("users");
    //TODO: check if credential are valid
    //TODO: perform authentication
    res.status(200).send({msg: "todo: implement this"});
});

// TODO: logout user '/api/user/logout'

/****** PROJECT COLLECTION *****************/
/**
 * schema:
 * {
 *   _id: ObjectId,
 *   owner: string,
 *   name: string,
 *   description: string,
 *   public: boolean
 *   dockerfile: string,
 *   github_url: string,
 *   github_auth_tokens: string,
 * }
 * note: also need username of owner in the request body: owner -> string
 * note: do not include _id in create new projects requests as this is auto-generated by mongodb
 */

// create a new project
// REQUIRES: JSON body matching project schema (and additionally owner -> string)
app.post('/api/project', express.json(), async (req, res) => {
    if (!check.isProject(req.body)) {
        res.status(400).send("invalid project in request body (as json)");
        return;
    }
    const projects = db.collection("projects");
    const users = db.collection("users");
    let ownerUser = await users.findOne({username: req.body.owner});
    if (!ownerUser) {
        res.status(400).send("user does not exist");
        return;
    }
    const result1 = await projects.insertOne(req.body);
    const insertedId = result1.insertedId.toString();
    if (!Array.isArray(ownerUser.project_ids)) {console.error("ownerUser.project_ids should br a string array");}
    ownerUser.project_ids.push(insertedId);
    const result2 = await users.updateOne({_id: ownerUser._id}, { $set: ownerUser});
    res.status(200).send(result2);
});

// get an existing project
// REQUIRES: JSON body with project id
app.get('/api/project', express.json(), async (req, res) => {
    if (!check.isString(req.body.id)) {
        res.status(400).send("need id -> string in request body");
        return;
    }
    const projects = db.collection("projects");
    const result = await projects.findOne({_id: new ObjectId(req.body.id)});
    if (!result ) {
        res.status(404).send(result);
        return;
    }
    res.status(200).send(result);
});

// set an existing project's fields (all of them except _id)
// REQUIRES: JSON body matching project schema and _id -> matching project to update
app.put('/api/project', express.json(), async (req, res) => {
    if (!check.isProjectPut(req.body)) {
        res.status(400).send("invalid project in request body (as json)");
        return;
    }
    const projects = db.collection("projects");
    req.body._id = new ObjectId(req.body._id);
    const result = await projects.updateOne({_id: req.body._id}, { $set: req.body});
    if (!result ) {
        res.status(404).send(result);
        return;
    }
    res.status(200).send(result);
});

// TODO: perform gitHub action on project '/api/project/deploy'

/****** Listen *****************/

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`);
});
